### ISSUE TITLE
Исправить замечания от SonarQube

### ISSUE THREAD

**Issue by 24const** [24const/photo-anthropology#11]
Требуется исправить все замечания от SonarQube и привести код к общим стандартам

Для отправки отчета в Sonar можно запустить следующую команду:
```
mvn sonar:sonar -Dsonar.host.url=http://sonar.intabia.ru -Dsonar.login=cf835ced6f64f0e209545b3ab811c2a6c312418c -Dsonar
.projectName=PhotoAnthropology -Dsonar.projectVersion=0.2.0 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2

```
Отчет будет сгенерирован и доступен в веб-интерфейсе сонара:
https://sonar.intabia.ru/dashboard?id=com.nsu%3Aphoto-anthropology

Требуется:
1. Исправить замечания типа Bug, Vulnerability, Code Smell иSeverity
2. Покрыть код тестами на 70% и комментариями

**Comment by GKsenya** [comment]
Исправлено!:)
