### ISSUE TITLE
Создать DAO слой приложений

### ISSUE THREAD

**Issue by 24const** [24const/photo-anthropology#3]
1. Создаем папку dao в src
2. Создаем классы ImageDAO, FileDAO, GroupDAO, TagDAO, для каждой сущности.
3. Каждый DAO класс может добавлять\удалять запись в соответствующей таблице

**Comment by GKsenya** [comment]
1. Папку dao создала 
2. Создала классы для каждой сущности
3. Реализовала добавление\удаление записей соответствующих таблиц классами dao
